version: "1"

services:
  web:
    build: 
      context: .
      dockerfile: flask_dockerfile
  db:
    image: "imxuanjun/solace_trust"
  user:
    build:
      context: .
      dockerfile: user_dockerfile
    stdin_open: true
    tty: true
    
